apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tek-xlr-data-webservice
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: tek-xlr-data-webservice
    spec:
      containers:
      - name: tek-xlr-data-webservice
        image: zulyian/tek-xlr-data-webservice:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
